### ISSUE TITLE
A separate patchset

### ISSUE THREAD

**Issue by birdie-github** [cyberus-technology/virtualbox-kvm#1]
I understand that it's supposed that people `git clone` this repo and build it however some would simply want to download the latest official VirtualBox tarball and apply a single patch to make it use KVM. Such a patch would also be easier to examine for any issues and assess the work that's been done.

So, it would be great and extremely helpful if you published such a patch separately or provided instructions how to generate it.

That would also be extremely useful for various Linux distros who may want to build and distribute KVM'ed VirtualBox.

**Comment by tpressure** [comment]
You can generated a patch like that from the cloned repo:

`git diff -u baa237b0d2ed1d715b8163ff2839301771fd3ab8 > vbox-kvm.patch`

**Comment by parthy** [comment]
Looking at the individual commits we added on top of the original import should also give you a good insight into the changes we've made. With `git format-patch`, you can also create the patch set if you prefer that over having one big patch file.

**Comment by blitz** [comment]
A separate patchset would indeed make packaging in distros easier.

**Comment by parthy** [comment]
I've added the complete patch as a single file to the release assets (untested so far): https://github.com/cyberus-technology/virtualbox-kvm/releases/download/dev-20240208/virtualbox-kvm-dev-20240208.patch

Does this help?

**Comment by blitz** [comment]
@parthy For the patch, it would be nice to see in the name to which upstream version it applies to. That would remove some surprises in case your distro version is still on 7.0.12 or ahead of us.

**Comment by parthy** [comment]
I've changed it to this: https://github.com/cyberus-technology/virtualbox-kvm/releases/download/dev-20240208/virtualbox-7.0.14-kvm-dev-20240208.patch

Or whould you prefer something else?

**Comment by blitz** [comment]
That's great! :+1:
