### ISSUE TITLE
Import Qemu VM

### ISSUE THREAD

**Issue by t0msk** [cyberus-technology/virtualbox-kvm#16]
I dont know where to ask, so I ask here, now when Virtualbox uses as KVM for virtualization, is possible to import into Virtualbox Qemu virtual machine? For that I was using virt-manager, so I wonder if I can use Virtualbox-kvm for it.

**Comment by parthy** [comment]
Even though KVM is now used for virtualization, the frontend responsible for managing the VMs still remains VirtualBox and not virt-manager. Apart from some limitations (#3), the big noticeable difference for users is that they don‘t need the kernel modules anymore and can run VirtualBox and Qemu side by side. The rest is meant to look and feel completely like standard VirtualBox.
