### ISSUE TITLE
Feature Request: Nested Virtualization

### ISSUE THREAD

**Issue by naY9yjoS6ZqhOd35sIFH** [cyberus-technology/virtualbox-kvm#19]
---
name: Feature Request Nested Virtualzation KVM-backend in VirtualBox 

---

### Bug Description

after enable Nested Virtualzation of exist VMs
it doesn't work with Nested Virtualzation in VMs

### How to Reproduce

```
mkdir -p /media/ramos/vbox
VBoxManage createvm --name x64zfs --default --basefolder=/media/ramos/vbox --ostype=Linux26_64 --register
VBoxManage modifyvm x64zfs --nested-hw-virt=on
```

### VM configuration

Guest OS configuration details:

* Bedrock Linux x86_64 
* with debian xanmod kernel 
* 6.6.21-x64v1-xanmod1 
* runs QEMU and VirtualBox-kvm too

Host OS details:

* Bedrock Linux 
* run with gentoo/debian kernel 
* and arch userland
* 6.6.21-gentoo-x86_64 
* 5.15.151-gentoo-x86_64 
* 6.6.21-x64v2-xanmod1

### Logs

each machine one reply

**Comment by naY9yjoS6ZqhOd35sIFH** [comment]
[VBox.log](https://github.com/cyberus-technology/virtualbox-kvm/files/14555754/VBox.log)
[cpu.txt](https://github.com/cyberus-technology/virtualbox-kvm/files/14555755/cpu.txt)
[dmesg.txt](https://github.com/cyberus-technology/virtualbox-kvm/files/14555758/dmesg.txt)
[x64zfs.vbox.txt](https://github.com/cyberus-technology/virtualbox-kvm/files/14555825/x64zfs.vbox.txt)

**Comment by tpressure** [comment]
Hi @naY9yjoS6ZqhOd35sIFH 

nested virtualization support is ongoing work and is currently not supported by the KVM-Backend for VirtualBox.

**Comment by tpressure** [comment]
You can try the following test branch for nested VMX (Intel). Note that SVM (AMD) is not supported right now.

https://github.com/tpressure/virtualbox-kvm/tree/nested_vmx_dev

To enable nested virtualization, you have to run `VBoxManage modifyvm <vm_name> --nested-hw-virt on`

**Comment by tpressure** [comment]
Nested virtualization for Intel systems is now officially supported with the latest release: https://github.com/cyberus-technology/virtualbox-kvm/releases/tag/dev-20240502

**Comment by naY9yjoS6ZqhOd35sIFH** [comment]
roger that,and AMD support is No worries. I'm in no hurry
