### ISSUE TITLE
Nix Support

### ISSUE THREAD

**Issue by nikstur** [cyberus-technology/virtualbox-kvm#2]
Do you plan to natively package this with Nix as well?

**Comment by blitz** [comment]
I can see what I can do tomorrow. Should be pretty trivial.

**Comment by blitz** [comment]
First tiny preparations: https://github.com/NixOS/nixpkgs/pull/287295

**Comment by blitz** [comment]
Once the above PR is through. I'll open another PR. In the meantime, there is `pkgs.virtualboxKvm` here: https://github.com/blitz/nixpkgs/tree/vbox-kvm-2

**Comment by blitz** [comment]
I'm updating VBox in nixpgks to the same version that the KVM version is based on here:
https://github.com/NixOS/nixpkgs/pull/287878

After that it should be easy to build a switch in the VirtualBox module to select which version you want.

**Comment by blitz** [comment]
https://github.com/NixOS/nixpkgs/pull/288579 <- It's missing a bit of work and the module is not tested at all at the moment, but might be good enough to try.

**Comment by blitz** [comment]
I finally finished the nixpkgs PR. Enjoy! Just waiting for reviews now.

**Comment by tpressure** [comment]
@blitz can we close this now that https://github.com/NixOS/nixpkgs/pull/288579 has been merged?

**Comment by blitz** [comment]
Yes!
