### ISSUE TITLE
Cannot start VM - Failed to construct device 'VfioDev' instance #0 (VERR_INVALID_PARAMETER)

### ISSUE THREAD

**Issue by Candunc** [cyberus-technology/virtualbox-kvm#20]
### Bug Description

Starting a VM appears to fail due to `00:00:01.128000 VFIO: Could not open VFIO Container` - however, vfio appears to be permissioned correctly (Even with a chmod to my own user to test):

```
$ ls -fl /dev/vfio/
total 0
drwxr-xr-x  2 root    root         60 Mar 16 13:33 .
drwxr-xr-x 19 root    root       3800 Mar 16 13:33 ..
crw-rw-rw-  1 candunc candunc 10, 196 Mar 16 13:33 vfio
```

```
00:00:01.127942 VFIO: Constructing VFIO PCI device with path /sys/bus/pci/devices/0000:00:02.2 Guest BDF: 00:10.0
00:00:01.127971 VFIO: Detected VFIO Api Version 0
00:00:01.127999 AssertLogRel /home/candunc/Downloads/VirtualBox-7.0.14/src/VBox/Devices/Bus/VfioDevice.cpp(78) int VfioDevice::initializeVfio(PPDMDEVINS, std::filesystem::__cxx11::path): vfioGroupFd > 0
00:00:01.128000 VFIO: Could not open VFIO Container
00:00:01.128001 AssertLogRel /home/candunc/Downloads/VirtualBox-7.0.14/src/VBox/Devices/Bus/VfioDevice.cpp(701) int VfioDevice::init(PPDMDEVINS, std::filesystem::__cxx11::path): RT_SUCCESS(rc)
00:00:01.128002 AssertLogRel /home/candunc/Downloads/VirtualBox-7.0.14/src/VBox/Devices/Bus/DevVfio.cpp(79) int devVfioConstruct(PPDMDEVINS, int, PCFGMNODE): RT_SUCCESS(rc)
00:00:01.128003 PDM: Failed to construct 'VfioDev'/0! VERR_INVALID_PARAMETER (-2) - Invalid parameter.
00:00:01.128009 VMSetError: /home/candunc/Downloads/VirtualBox-7.0.14/src/VBox/VMM/VMMR3/PDMDevice.cpp(554) int pdmR3DevInit(PVM); rc=VERR_INVALID_PARAMETER
00:00:01.128010 VMSetError: Failed to construct device 'VfioDev' instance #0
00:00:01.132696 AssertLogRel /home/candunc/Downloads/VirtualBox-7.0.14/src/VBox/Devices/Bus/VfioDevice.cpp(834) int VfioDevice::terminate(PPDMDEVINS): RT_SUCCESS(rc)
00:00:01.188470 GIM: KVM: Resetting MSRs
00:00:01.643477 ERROR [COM]: aRC=NS_ERROR_FAILURE (0x80004005) aIID={6ac83d89-6ee7-4e33-8ae6-b257b2e81be8} aComponent={ConsoleWrap} aText={Failed to construct device 'VfioDev' instance #0 (VERR_INVALID_PARAMETER)}, preserve=false aResultDetail=-2
00:00:01.643743 Console: Machine state changed to 'PoweredOff'
00:00:01.653315 Power up failed (vrc=VERR_INVALID_PARAMETER, hrc=NS_ERROR_FAILURE (0X80004005))
00:00:01.655042 GUI: UIMachineViewNormal::resendSizeHint: Restoring guest size-hint for screen 0 to 800x600
00:00:01.655074 ERROR [COM]: aRC=E_ACCESSDENIED (0x80070005) aIID={4680b2de-8690-11e9-b83d-5719e53cf1de} aComponent={DisplayWrap} aText={The console is not powered up (setVideoModeHint)}, preserve=false aResultDetail=0
00:00:01.655132 GUI: Aborting startup due to power up progress issue detected...
00:00:01.662812 GUI: UICommon: Handling aboutToQuit request..
00:00:02.626058 GUI: UICommon: aboutToQuit request handled!
```

### How to Reproduce

Fresh install of Debian and Windows 10 LTSC 21H2 with a 12th Gen Intel(R) Core(TM) i7-1260P

Followed instructions, self-compiled VirtualBox and modified Linux Kernel.

### VM configuration

Guest OS configuration details:

* Guest OS type and version: Windows 10 LTSC 21H2
[Windows.vbox.txt](https://github.com/cyberus-technology/virtualbox-kvm/files/14625079/Windows.vbox.txt)

Host OS details:

* Host OS distribution: 
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 12 (bookworm)
Release:        12
Codename:       bookworm
```

* Host OS kernel version: 6.6.15-sriov

### Logs

[VBox.log](https://github.com/cyberus-technology/virtualbox-kvm/files/14625074/VBox.log)
[dmesg.txt](https://github.com/cyberus-technology/virtualbox-kvm/files/14625075/dmesg.txt)

**Comment by parthy** [comment]
Thanks for your interest in SR-IOV graphics! At first glance, it looks like the `vfio-pci` driver did not attach to the VFs, instead the `i915` took control. If you could be so kind and check some things for us:

1. According to the kernel log, the additional PCI IDs are added to `vfio-pci` very early on:
`[    4.608507] vfio_pci: add [8086:46a6[ffffffff:ffffffff]] class 0x000000/00000000`
Are you running the command `echo "<vendor-id> <device-id>" > /sys/bus/pci/drivers/vfio-pci/new_id` manually or did you configure `vfio-pci` through other means?
2. Could you verify if `lspci -v -s 0:2.1` shows `i915` or `vfio-pci` as active kernel driver?
3. Could you try disabling the `sriov_drivers_autoprobe` parameter of `i915` before activating the VFs:
```
echo 0 | sudo tee /sys/bus/pci/devices/0000\:00\:02.0/sriov_drivers_autoprobe
echo 7 | sudo tee /sys/class/drm/card0/device/sriov_numvfs
echo 1 | sudo tee /sys/bus/pci/devices/0000\:00\:02.0/sriov_drivers_autoprobe
```

Key point is: I think we need to get `vfio-pci` to take control of the VFs in order for the assignment to work.

**Comment by Candunc** [comment]
Thanks for your assistance!

I think there is something missing in plain Debian that Ubuntu takes care of, or there's something missing in the SR-IOV instructions. I have to run `modprobe vfio-pci` in order to expose the /sys/bus/pci/drivers/vfio-pci 'folder', so part of my earlier debugging was enabling it (and assigning the GPU id) early in the boot process.

I don't see the `i915 0000:00:02.0: enabling device` line in my dmesg, so perhaps that is a clue.

Reverting those changes and running your commands I get the following (with no driver assigned instead of the expected vfio-pci)

```
root@framework:~# modprobe vfio-pci
root@framework:~# lspci -s 0:2.0 -n
00:02.0 0300: 8086:46a6 (rev 0c)
root@framework:~# echo "8086 46a6" > /sys/bus/pci/drivers/vfio-pci/new_id
root@framework:~# echo 0 > /sys/bus/pci/devices/0000\:00\:02.0/sriov_drivers_autoprobe 
root@framework:~# echo 7 > /sys/class/drm/card0/device/sriov_numvfs
root@framework:~# echo 1 > /sys/bus/pci/devices/0000\:00\:02.0/sriov_drivers_autoprobe 
root@framework:~# lspci -v -s 0:2.1
00:02.1 VGA compatible controller: Intel Corporation Alder Lake-P Integrated Graphics Controller (rev 0c) (prog-if 00 [VGA controller])
        Subsystem: Framework Computer Inc. Alder Lake-P GT2 [Iris Xe Graphics]
        Flags: fast devsel, IOMMU group 18
        Memory at 4010000000 (64-bit, non-prefetchable) [disabled] [size=16M]
        Memory at 4020000000 (64-bit, prefetchable) [virtual] [size=512M]
        Capabilities: [70] Express Root Complex Integrated Endpoint, MSI 00
        Capabilities: [ac] MSI: Enable- Count=1/1 Maskable+ 64bit-
        Kernel modules: i915
```

One thing to note is vfio-pci does seem to be operational:

```
candunc@framework:~$ lsmod | grep vfio
vfio_pci               16384  0
vfio_pci_core          86016  1 vfio_pci
vfio_iommu_type1       49152  0
vfio                   65536  3 vfio_pci_core,vfio_iommu_type1,vfio_pci
irqbypass              12288  2 vfio_pci_core,kvm
```

[dmesg.log](https://github.com/cyberus-technology/virtualbox-kvm/files/14628917/dmesg.log)

Edit:
Looks like I can get it working by forcing the vfio-pci driver by executing the following:

```
root@framework:~# echo "vfio-pci" > /sys/bus/pci/devices/0000\:00\:02.1/driver_override
root@framework:~# echo "0000:00:02.1" > /sys/bus/pci/drivers/vfio-pci/bind
```

![Screenshot_20240317_155405](https://github.com/cyberus-technology/virtualbox-kvm/assets/549161/0c9b19a8-4b47-49f0-bc9d-5d3063e08938)

**Comment by tpressure** [comment]
Just an FYI because I have seen the following in your VirtualBox log file: 

```
GIM: Using provider 'KVM' (Implementation version: 0)
```

KVM is not the correct GIM provider for Windows guests. Please use HyperV or default if you want good performance (Settings->System->Acceleration->Paravirtualization Interface). This setting has no relations to the KVM backend itself.

**Comment by tpressure** [comment]
Closing this because @Candunc got this working. Feel free to reopen if you feel the issue has not been resolved yet.
