### ISSUE TITLE
Missing `git init` in build instructions

### ISSUE THREAD

**Issue by Windows98SE-dev** [cyberus-technology/virtualbox-kvm#22]
### Bug Description

You just get a Not a git repo when trying to run any of the git commands except for the clone one

### How to Reproduce

Follow the script 

### VM configuration

Guest OS configuration details:

* Windows 11 23H2
*Not any since it is WSL2 

Host OS details:

*Ubuntu
*5.15.146.1-microsoft-standard-WSL2+

### Logs

Following logs are required:

* Don't know how to see
* Not any

**Comment by amstelchen** [comment]
`git init` missing in the build instructions, probably.

**Comment by tpressure** [comment]
@amstelchen is correct. The readme is missing the `git init` command. We will update this soon.

**Comment by tpressure** [comment]
Readme has been updated.

**Comment by Windows98SE-dev** [comment]
Ok thanks !
