### ISSUE TITLE
VBoxNetAdpCtl outright doesn't work/can't create host-only network

### ISSUE THREAD

**Issue by jchv** [cyberus-technology/virtualbox-kvm#27]
### Bug Description

Attempting to create a host-only network gives the following error:

![Error screenshot, "VBoxNetAdpCtl: Error while adding new interface: failed to open /dev/vboxnetctl: No such file or directory."](https://github.com/cyberus-technology/virtualbox-kvm/assets/938744/592f3d07-92c2-4ed7-8154-c78cec9a9373)

I understand that networking is not the priority here, but it's unclear _how_ one can even create a host-only network. Is it possible? I have been spelunking the Virtualbox source code to no avail trying to figure out how this might work in driverless mode. I would be very grateful if I could get some pointers!

The message about networking in the README doesn't imply that host-only networking _can't_ work, but if it can't right now, maybe it would be good to explicitly add that to the note about networking. :(

### How to Reproduce

Try to create a host-only network in the UI.

You can also reproduce it directly via the `VboxNetAdpCtl` command:

```sh
$ VBoxNetAdpCtl add
VBoxNetAdpCtl: Error while adding new interface: failed to open /dev/vboxnetctl: No such file or directory
```

### VM configuration

(Not applicable.)

**Comment by tpressure** [comment]
Unfortunately, it's not possible right now and we currently don't have funding to work on a good solution for bridged and host-only networking ( see #25 ).

Since this is a question that we get a lot from the community, we just enabled [github-sponsors ](https://github.com/sponsors/cyberus-technology). If we get sufficient momentum, we would be able to provide a nice networking solution that works identical to vanilla VirtualBox.

**Comment by jchv** [comment]
For what it's worth, I *did* wind up joining the sponsors since VirtualboxKVM is my preferred way to use VBox, but it seems, unfortunately, that nobody else has followed suit. Here's to hoping some day the networking issue can see some improvements in some way. (Or maybe the KVM backend can even be upstreamed? I certainly wish.)

**Comment by tpressure** [comment]
@jchv we are very well aware of your sponsorship. Thanks a lot for doing this, it's very much appreciated. 

Side note: you can do bridged networking with virtualbox-kvm, but it does not work as easy as with the `vboxnetadp` kernel module. You have to setup a tun/tap device, and configure the bridge via the command line.
