### ISSUE TITLE
GPU Virtualization support (Intel GVT-g)

### ISSUE THREAD

**Issue by ghost** [cyberus-technology/virtualbox-kvm#28]
Feature request: GVT-g support in the KVM backend for VirtualBox

https://wiki.archlinux.org/title/Intel_GVT-g

related:
https://github.com/cyberus-technology/virtualbox-kvm/issues/24
https://github.com/cyberus-technology/virtualbox-kvm/blob/dev/README.intel-sriov-graphics.md

**Comment by tpressure** [comment]
@read8873 what exactly is the issue here? Are you asking for GVT-g support in the KVM backend for VirtualBox?

**Comment by ghost** [comment]
> what exactly is the issue here? 

sorry, I mistakenly delele the first line when pasting the link.

>  Are you asking for GVT-g support in the KVM backend for VirtualBox?

Yes. SR-IOV only support some very new graphics cards. GVT-g will allow more options.

It would also be nice to add some instructions or link to a README.md on VirtualBox-kvm UI for how to configure GVT-g on the host

**Comment by tpressure** [comment]
We had this question before, see https://github.com/cyberus-technology/virtualbox-kvm/issues/7

> Unfortunately, Intel GVT-g is dead technology and has lots of issues which prevents it from being used in production (see https://github.com/intel/gvt-linux/issues/153 and https://github.com/intel/gvt-linux/issues/188).
>
> We had support for it a while ago, but dropped it because these issues will never be fixed by Intel.

We tried really hard to convince Intel to fix these problems but they will never do it. So unfortunately, there's no way forward with this technology :(

**Comment by tpressure** [comment]
Currently, the only way is to use a recent system (Alder Lake, Raptor Lake) and use SR-IOV graphic virtualization. It works quite well, but it is not mainline yet, so you need a modified Linux kernel in order to use it successfully.

**Comment by tpressure** [comment]
Closing this because we won't support GVT-g unless Intel fixes the issues mentioned above.

**Comment by ghost** [comment]
Will virtualbox-kvm support Virtio GPU 3D acceleration? @tpressure  
https://github.com/virtio-win/kvm-guest-drivers-windows/pull/943

**Comment by tpressure** [comment]
> Will virtualbox-kvm support Virtio GPU 3D acceleration? @tpressure [virtio-win/kvm-guest-drivers-windows#943](https://github.com/virtio-win/kvm-guest-drivers-windows/pull/943)

Although we have a virtio-gpu model, virgl is not supported at the moment.
