### ISSUE TITLE
3D acceleration doesn't work

### ISSUE THREAD

**Issue by ilya-fedin** [cyberus-technology/virtualbox-kvm#29]
### Bug Description

As soon as I enable 3D acceleration, I get the following error:
```
Error code: NS_ERROR_FAILURE (0X80004005)
Component: SessionMachine
Interface: ISession {c0447716-ff5a-4795-b57a-ecd5fffa18a4}
```

### How to Reproduce

Just enable 3D acceleration

### VM configuration

Guest OS configuration details:

* Ubuntu 24.04
* [Ubuntu.vbox.txt](https://github.com/cyberus-technology/virtualbox-kvm/files/15388787/Ubuntu.vbox.txt)

Host OS details:

* NixOS unstable
* 6.7.9-lqx1

### Logs

* [dmesg.txt](https://github.com/cyberus-technology/virtualbox-kvm/files/15388802/dmesg.txt)
* [VBox.log](https://github.com/cyberus-technology/virtualbox-kvm/files/15388861/VBox.log)

(The logs have multiple attempts to run with 3D acceleration and multiple runs without 3D acceleration)

**Comment by tpressure** [comment]
Hi @ilya-fedin 

thanks for the bug report. Unfortunately, the log only contains the last run of the VM which was without 3D acceleration enabled: ` 3DEnabled <integer> = 0x0000000000000000 (0)`

Can you please re-enable 3D acceleration on your end and upload a new `VBox.log` file?

**Comment by ilya-fedin** [comment]
Oops, I thought it renames the logs per VirtualBox run but apparently per VM run actually. I replaced the file with an older one.

**Comment by ilya-fedin** [comment]
Oh, now I see it needs vulkan. Will try to make it find it.

**Comment by tpressure** [comment]
The error is the following:

```
00:00:03.223187 rtldrNativeLoad: dlopen('D3DCompiler_47.so', RTLD_NOW | RTLD_LOCAL) failed: D3DCompiler_47.so: cannot open shared object file: No such file or directory
00:00:03.223193 VMSVGA: Single DX device mode: enabled
00:00:03.223700 rtldrNativeLoad: dlopen('libvulkan.so.1', RTLD_NOW | RTLD_LOCAL) failed: libvulkan.so.1: cannot open shared object file: No such file or directory
```

I haven't tested 3D acceleration on NixOS yet, but I will try it on Ubuntu later today to see whether this is a general problem.

**Comment by ilya-fedin** [comment]
> Oh, now I see it needs vulkan. Will try to make it find it.

It helped. Sorry for the noise.

**Comment by tpressure** [comment]
Can you maybe add a sentence or two how you solved the issue? Just to document this if other people run into the same scenario.

**Comment by ilya-fedin** [comment]
Well, I found the path to the vulkan library with `nix-store -r (nix-instantiate -A vulkan-loader '<nixpkgs>')` and then ran virtualbox with `LD_LIBRARY_PATH=<that path>/lib` set. This is good only as a temporary workaround though, I reported it to nixpkgs as https://github.com/NixOS/nixpkgs/issues/313372 and once fixed it should just work.
