### ISSUE TITLE
Feature Request: What If porting macOS/Arm64 with Linux/Arm64 KVM-backend 

### ISSUE THREAD

**Issue by naY9yjoS6ZqhOd35sIFH** [cyberus-technology/virtualbox-kvm#35]
### Bug Description

upstream oracle's VirtualBox has new feature of macOS/Arm64 and can run Linux/FreeBSD on their platform
and i have an idea what if porting it with Linux/Arm64 KVM-backend for user-friendly interface

### How to Reproduce

Not avaliable now

**Comment by flyfloh** [comment]
Hi, thanks for the idea. Unfortunately this port would be quite the undertaking and we do not have the bandwidth to do that at the moment.
