### ISSUE TITLE
vbox 7.1.2 compile - "error: patch failed: Config.kmk:1996" "error: Config.kmk: patch does not apply"

### ISSUE THREAD

**Issue by jmergy** [cyberus-technology/virtualbox-kvm#37]
Trying to compile with virtualbox 7.1.2 source. Just not able yet? 7.0.x working fine. 

`
`# git am ../vbox-kvm/patches/*.patch
Applying: NEM: Implement KVM backend
error: patch failed: Config.kmk:1996
error: Config.kmk: patch does not apply
error: patch failed: include/iprt/x86.h:686
error: include/iprt/x86.h: patch does not apply
error: patch failed: src/VBox/VMM/VMMR3/CPUMR3CpuId.cpp:1390
error: src/VBox/VMM/VMMR3/CPUMR3CpuId.cpp: patch does not apply
error: patch failed: src/VBox/VMM/VMMR3/EM.cpp:219
error: src/VBox/VMM/VMMR3/EM.cpp: patch does not apply
error: patch failed: src/VBox/VMM/VMMR3/NEMR3Native-linux.cpp:37
error: src/VBox/VMM/VMMR3/NEMR3Native-linux.cpp: patch does not apply
error: patch failed: src/VBox/VMM/VMMR3/PDMDevMiscHlp.cpp:34
error: src/VBox/VMM/VMMR3/PDMDevMiscHlp.cpp: patch does not apply
error: patch failed: src/VBox/VMM/include/GIMHvInternal.h:1100
error: src/VBox/VMM/include/GIMHvInternal.h: patch does not apply
error: patch failed: src/VBox/VMM/include/NEMInternal.h:35
error: src/VBox/VMM/include/NEMInternal.h: patch does not apply
Patch failed at 0001 NEM: Implement KVM backend
hint: Use 'git am --show-current-patch=diff' to see the failed patch
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".`

**Comment by parthy** [comment]
Yes, you are correct that the patch set is currently created against VirtualBox 7.0. We did not look into 7.1 yet.

**Comment by jmergy** [comment]
Thanks @parthy  - all good with vbox-kvm and 7.0.x but would be cool at some point.

**Comment by limbo127** [comment]
vbox 7.1.x is very progressing in wayland support  . Thank for the effort

**Comment by jmergy** [comment]
Feeling like this is a dead-end kind of thing. Had potential and performance was great on the initial release.

**Comment by tpressure** [comment]
> Feeling like this is a dead-end kind of thing. Had potential and performance was great on the initial release.

We still maintain this project, it's just not a number one priority for us right now.

**Comment by jmergy** [comment]
Thanks!

**Comment by tpressure** [comment]
We have release a new patch series with 7.1.4 support
