### ISSUE TITLE
hide kvm

### ISSUE THREAD

**Issue by nhamhuynh79** [cyberus-technology/virtualbox-kvm#38]
Can we hide kvm in windows guest?

**Comment by parthy** [comment]
Windows guests should use the Hyper-V paravirtualization feature by default. The backend in use (Oracle HV or KVM) is independent of the paravirtualization interface the guest sees. Could you specify your VM settings and what exactly you are seeing and trying to change?

**Comment by nhamhuynh79** [comment]
some things like anti detect vm to run game with anti cheat.

**Comment by tpressure** [comment]
Principle, you can "hide" KVM by selecting 'None' as paravirtualization provider. This removes the HV bit from CPUID and disables the KVM capability MSRs. I don't know whether this is enough for anti-cheat though. What would you do if you want to achieve the same thing with Qemu?
