### ISSUE TITLE
Javascript leak or user error?

### ISSUE THREAD

**Issue by amd1890** [cyberus-technology/virtualbox-kvm#41]
I am trying to create a new account on a platform that tends to ban new users because it thinks everyone is some seo scammer hacker type. I want to use this account for personal use but don't want to open it with a phone or some other way because I prefer privacy.

I use UTC for my computer as a whole, but inside this VM I am trying to have it match the IP address I have so I don't get blocked right away. When I go to different websites to check to see if they think I seem like a bot, the javascript test my time and are getting UTC from outside the box. The IP is set to CH and the clock is set to CH time inside the VM. There really shouldn't be any way for them to know I prefer UTC outside the VM.  It's possible I am incorrect about this, but it seems like the implementation of KVM in this either isn't fully sandboxing all the javascript or I am fundamentally making some sort of error in misunderstanding. The VM had an official closed source Windows OS installed that had not been modified in any illegal or unusual way to disable telemetry that could upset Microsoft, owner of the github platform.

I am a low skill user and non-developer and it's very likely this is my error.

**Comment by snue** [comment]
Sorry to hear about the trouble with the account creation. It doesn't sound like an issue with the overall virtualization or the KVM backend though. Did it behave differently when running the same VM image with the unmodified VirtualBox (with the vboxdrv kernel modules)? "The IP" you mention is probably the public IPv4 address of your internet connection? That would match for all the devices in your home network, including any virtual machines behind NAT networking by default. At least as long as you are not using an extra VPN service.

I have no idea how the respective JavaScript is determining the time zone of your system, and whether a "mismatch" there is causing the platform's "we don't talk to you" behavior. But I find it highly unlikely that it leaked the timezone info from the host into the Windows VM. I'd rather suspect a privacy-enhancing browser extension to obfuscate the result to prevent fingerprinting. Timezone info should either be retrieved via the IP geolocation or the info provided by the web browser (which should query the OS settings). Both are not perfectly reliable indicators though.

**Comment by amd1890** [comment]
It was supposed to be looking at the IP of my Internet address, which had been changed with a VPN, and compare it to the time of the VM (which was changed automatically to match the time of the VM). These values were both the same at the time. IP address was a certain country, time was a certain country. Outside the VM, I am using another time zone. When the javascript was run, it detected the timezone outside the VM that was slightly different. If this "test" website does this, than any website trying to test if account creation is "real" or "bot/SEO" is going to reject the new account.

Many companies rely on javascript to try to implement a 1 account per 1 user/machine standard (using canvas fingerprints, WebGL, audiocontext fingerprints, screen resolutions, etc to determine if the machine is the same machine). They occasional allow alts for the same machine, not letting the user know the sites are completely aware these alts are the same machine and likely the same person. The Internet used to be about freedom and connection and it's just turned into an en****ified effort to track everyone using javascript and many sites block Tor for signup. The "What is your REAL IP time zone compared to javascript IP timezone?" is just more en****ifying javascript to try to make it hard to register if not on a residential IP and using Chrome with no alterations.

I'm just not used to the javascript somehow leaking to be able access the time zone of the OS. Perhaps there was something else that went on that explains it. I did not do a similar test without KVM for VirtualBox to see if the same problem occurs, however.

**Comment by flyfloh** [comment]
I agree with @snue: It's highly unlikely that the hosts timezone info leaks from your Linux host into your Windows guest.

In any case if this was the case it is by no means likely that the issue is located in this KVM Backend for VirtualBox. It could be in VirtualBox's userland part or in KVM. If you want to check please try to reproduce your issue with

* unmodified Oracle VirtualBox
* KVM/Qemu

If you can reproduce this issue with *really only* this backend we can re-open this issue.
