### ISSUE TITLE
QT-6 fail

### ISSUE THREAD

**Issue by atagtm** [cyberus-technology/virtualbox-kvm#43]
Yesterday everything was fine (v7.0.22), today.... Qt6 makes it impossible

> kmk: *** No rule to make target '/opt/Qt/6.8.1/gcc_64//lib/libQt6StateMachine.so', needed by '/home/me/git/vbox/VirtualBox-7.1.4/out/linux.amd64/release/obj/UICommon/UICommon.so'.  Stop

Any ideas?
ofc i have a "standard" installation of Qt in /opt/Qt

gcc (Ubuntu 11.4.0-9ubuntu1) 11.4.0 -> it was fine yesterday (with v7.0.22)

**Comment by tpressure** [comment]
We didn't change anything in that regard.

Are you able to compile the [vanilla source](https://download.virtualbox.org/virtualbox/7.1.4/VirtualBox-7.1.4.tar.bz2) without our patches?

**Comment by atagtm** [comment]
The only change was in the README.md about the vanilla version... i keep tryin', brb

...

The answer is NO, vanilla version also fails on Qt6 (6.8.1) 0.o

**Comment by tpressure** [comment]
> The answer is NO, vanilla version also fails on Qt6 (6.8.1) 0.o

Then the issue is not related to the KVM patch set.

**Comment by TheHooly** [comment]
> > The answer is NO, vanilla version also fails on Qt6 (6.8.1) 0.o
> 
> Then the issue is not related to the KVM patch set.

Though that also means that the build instructions in the README are outdated.

Case in point, the described instructions for Ubuntu 22.04 fail due to Qt6, while attempting to build with Fedora 41 after `dnf builddep VirtualBox` fails with `Checking for Python support: 
 ** Python not found!`, despite `python-devel` being installed.

**Comment by tpressure** [comment]
> Though that also means that the build instructions in the README are outdated.

That is true. We kinda updated the patches in a hurry shortly before Christmas. We will update the readme soon.

**Comment by atagtm** [comment]
Ok, found the solution today. My Qt6 install is in $HOME/Qt and i had to add `--with-qt-dir=$HOME/Qt/Tools/QtDesignStudio/qt6_design_studio_reduced_version` to the configure command.
The "standard" lib folder of Qt doesn't have the libQt6StateMachine.so library, the above one does.

PS: python2-dev is obsoleted and no longer needed, remove it from the command line :)
