### ISSUE TITLE
Slackware64-current Compile Error

### ISSUE THREAD

**Issue by mdinslage** [cyberus-technology/virtualbox-kvm#5]
### Bug Description

Failing to compile on Slackware-current

Host OS details:
Slackware64-current
Kernel 6.6.15

First off, this looks like a real promising and cool project, thanks for it.  I was able to compile it no problem in Ubuntu 22.04 as per your instructions, but I am a Slackware user so I thought I would give it a try there.  I am using a modified version of the official third party SlackBuild located at www.slackbuilds.org.  This issue is not that pressing since I am sure you guys have other priorities, but I thought I would go ahead and report it just to see if anyone had any ideas.  I am using gcc 13 which I know could cause issues, but FWIW here is my build log.

### Logs
https://pastebin.com/RrnzXA88

**Comment by mdinslage** [comment]
So I decided to toss out the SlackBuild and just follow your instructions and build it manually.  I got a little farther along.  But again, I know you guys probably have your hands full so feel free to close this thread and disregard,  I am mostly just wanting to try it out and I can always do that in Ubuntu, I just thought it would be fun trying to get it to compile in Slackware64-current
https://pastebin.com/bErq5CLT

**Comment by parthy** [comment]
Thanks for trying and reporting your progress!

Yes, the errors with GCC 13 look familiar. We haven't gotten around to looking into that and potentially fixing it. We are currently building with GCC <= 12. In the [VirtualBox forum](https://forums.virtualbox.org/viewtopic.php?t=110128), someone also installed GCC 12 to get a successful build.

If we find out more or even have a fix, we will provide an update.

**Comment by parthy** [comment]
There already seems to be some ongoing work out there (including Oracle's SVN): https://github.com/NixOS/nixpkgs/pull/280675/files

Maybe that helps in the meantime?

**Comment by ernibert** [comment]
I'm on a LFS (Linux From Scratch) machine with gcc-13.2.0 - no issues compiling. To get around the uint32_t issue i did a
`    sed -e "/cstring/a #include <cstdint>" -i src/libs/dxvk-native-1.9.2a/src/util/util_bit.h    `
and applied Arch's https://gitlab.archlinux.org/archlinux/packaging/packages/virtualbox/-/blob/main/019-libxml-2-12.patch (when using libxml2 >= 2.12) which is there for 3 weeks now.

It compiled fine but when starting VirtualBox, it still complains about module vboxdrv is not loaded. But thats another story...

**Comment by mdinslage** [comment]
Slackware64-current also uses libxml-2.12.  I ran into that issue a few weeks back with regular Virtualbox so I was expecting that one and had the patch ready.   I will try both your suggestions when I get home tonight.

Thanks :)

**Comment by mdinslage** [comment]
> There already seems to be some ongoing work out there (including Oracle's SVN): https://github.com/NixOS/nixpkgs/pull/280675/files
> 
> Maybe that helps in the meantime?

Thank you sir, those two patches did the trick. I just successfully compiled it in Slackware64-current and now I am going to work on making a proper Slackware package.  Couple of questions, do I need to set KVM as the paravirtualization interface in "system>acceleration" or will it automatically default to it?  Also is PCI-Passthrough available yet, I don't see it in options?

Thanks again.

**Comment by parthy** [comment]
That's great news! The paravirtualization interface is independent of the hypervisor backend. It should be set to match the guest OS (or left on default).

PCI pass-through is theoretically available, but at the current time incomplete and not officially supported. It is only available via command-line (VBoxManage).
