### ISSUE TITLE
What are the steps to create a VM? (Getting `NS_ERROR_FAILURE` when booting a new Linux VM)

### ISSUE THREAD

**Issue by antermin** [cyberus-technology/virtualbox-kvm#6]
### Bug Description

I replaced distro-provided VirtualBox with VirtualBox KVM.

However, I am unable to boot a newly-created VM under VirtualBox KVM. Booting it under the original VirtualBox is fine though.

Are there any extra steps / configuration to make a VM compatible with VirtualBox KVM?

### How to Reproduce

1. Build and install VirtualBox KVM (I used the [AUR package](https://aur.archlinux.org/packages/virtualbox-kvm))
2. Create a new Linux VM in VirtualBox KVM
3. Try to boot the VM (but it always results in error, e.g. `NS_ERROR_FAILURE`)

Note: I have tried rebuilding with `--disable-hardening --disable-java` added, but it still fails to boot the VM.

### VM configuration

Guest OS configuration details:

* Type: Linux, Version: Linux 2.6 / 3.x / 4.x / 5.x (64-bit)
* [Guest VM configuration file](https://gist.github.com/antermin/53e5088c777beb101915af40c54fda61)

Host OS details:

* Arch Linux
* Kernel 6.7.4-arch1-1

### Logs

* I have checked `dmesg` but it has nothing relevant to the issue.
* There is also no VirtualBox log: `No log files for the machine linux found.`

**Comment by blitz** [comment]
Have you checked that KVM is available? You should see `/dev/kvm` on your system with permissions that allow you to access it.

Can you post the kernel log from your system together with `lsmod` output?

Typically there should be logs in `~/VirtualBox VMs/<your VM>`. You could also build VBox with `--build-debug` to get additional logging (this has some issues though unrelated to the KVM backend and you should not use it besides debugging this issue).

**Comment by antermin** [comment]
1. I can see `/dev/kvm` and I can also run VMs with `qemu-system-x86_64 -enable-kvm`:
```
crw-rw-rw-   1 root kvm        10, 232 Feb  9 19:36 kvm
crw-rw----   1 root kvm        10, 125 Feb  9 19:36 udmabuf
crw-rw-rw-   1 root kvm        10, 238 Feb  9 19:36 vhost-net
crw-rw-rw-   1 root kvm        10, 241 Feb  9 19:36 vhost-vsock
```

2. Please refer to [this gist](https://gist.github.com/antermin/d31aa955c3d2236f003a35077c2c1b06)
3. I only have `linux.vbox` and `linux.vbox-prev` in the directory.
 
Edit: I tried rebuilding with `--build-debug` but it failed with `undefined reference to 'soap_open_logfile'` even though `gsoap-2.8.132-1` is installed.

**Comment by tpressure** [comment]
Can you please try to start your VM via command line and check whether you get a useful error then?

`VirtualBoxVM --startvm <vm_name>`.

**Comment by antermin** [comment]
> Can you please try to start your VM via command line and check whether you get a useful error then?
> 
> `VirtualBoxVM --startvm <vm_name>`.

Somehow it failed like this:
```
Qt FATAL: FATAL: The application binary appears to be running setuid, this is a security hole.
Aborted (core dumped)
```

**Comment by blitz** [comment]
Are you trying to run VirtualBox as root?

**Comment by tpressure** [comment]
Seems like the VirtualBoxVM binary has the `s` bit set. 

As a workaround, you can try `chmod -s /path/to/your/VirtualBoxVM`.

**Comment by antermin** [comment]
> Seems like the VirtualBoxVM binary has the `s` bit set.

Thank you so much!

After `chmod -s /path/to/your/VirtualBoxVM`, the issue is gone and the VM can be booted.
