### ISSUE TITLE
Questions about graphics configuration

### ISSUE THREAD

**Issue by antermin** [cyberus-technology/virtualbox-kvm#9]
1. If you have a dedicated / discrete GPU (AMD / NVIDIA / Intel Xe MAX / Intel Arc), can you passthrough it? If yes, what are the steps?
2. For the "Graphics Controller" setting, which one should we use in different scenarios (guest OS, host GPU, etc.)? There are 2 new options but I am not sure which one to choose.

https://github.com/cyberus-technology/virtualbox-kvm/blob/471c213b5c13f6e25ed7af4b47472296a04bc871/src/VBox/Main/idl/VirtualBox.xidl#L6539-L6544

```
    <const name="VGAWithVirtioGpu" value="7">
      <desc>Virtualbox VGA device for the boot screen switching to Intel HD Graphics.</desc>
    </const>
    <const name="VirtioGpu" value="8">
      <desc>Intel HD Graphics with hardware acceleration.</desc>
    </const>
```

**Comment by parthy** [comment]
PCI pass-through is currently still under development and therefore experimental. It can be done with the `VBoxManage --attach-vfio` setting, but be prepared that it won't work out of the box.

As for the graphics controller choices, those two are actually meant to be used for Intel's SR-IOV graphics (https://github.com/intel/Display-Virtualization-for-Windows-OS). For normal operation, you probably want to stick to the standard VirtualBox options (VBoxSVGA or VMSVGA).
